logging:
  level:
    web: debug

resilience4j:
  ratelimiter:
    configs:
      default:
        limitForPeriod: 10
        limitRefreshPeriod: 60s
        timeoutDuration: 0
        registerHealthIndicator: true
        eventConsumerBufferSize: 100
    instances:
      simpleRateLimit:
        base-config: default
management:
  health:
    ratelimiters:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'